name: weather
description: A Weather CLI tool using OpenWeather API.
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.4.2
  equatable: ^2.0.5
  http: ^1.1.0
  mason_logger: ^0.2.10

  


dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.1
  test: ^1.21.0
  very_good_analysis: ^5.1.0


executables:
  weather: